### ISSUE TITLE
[BUG] 발자국 소리 미입력시에도 계속 나는 버그

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#112]
# 1. 버그 개요
- 발자국 소리 미입력시에도 계속 나는 버그
# 2. 버그 발생 일자
- 2024.11.03. 11:48
# 3. 버그 발생 상황 설명
- A or D 키를 누르지 않았음에도 발자국 소리가 연속적으로 재생되는 버그 발견
# 4. 예상되는 문제
- code에서 문제 있는듯 함
# 5. 필요한 조치
- 키 입력시에만 재생되도록 수정
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)
- Window 11 / Unity 2021.3.42f1

**Comment by ohjh1744** [comment]
ActBaseWalk 쪽에서 조건 및 코드 추가하여
정지상태에서도 WalkSound가 들리는 BUG Fix했습니다.
