### ISSUE TITLE
[BUG] BASE 캐릭터 RAYCAST 오류

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#113]
# 1. 버그 개요
- BASE 캐릭터가 플랫폼 모서리에 멈출 시 조작이 불가능해짐
# 2. 버그 발생 일자
- 2024.11.04 12:28
# 3. 버그 발생 상황 설명
- 플랫폼 모서리에 BASE 캐릭터가 멈출 시 AD 조작 불가능
 # 4. 예상되는 문제
- RAYCAST거리가 짧아서 플랫폼을 인식하지 못하는 문제로 예상
# 5. 필요한 조치
- RAYCAST 거리 조절 필요
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)
- Window 11 / Unity 2021.3.42f1

**Comment by yootaeheon** [comment]
문제 해결 완료하였습니다

RAYCAST가 얇아서 Platform 끝자락에 서 있을때 닿지 않는 문제 확인하여, isGround 확인하는 방식을 RAYCAST를 OverlapSpere로 변경하여 해결했습니다
