### ISSUE TITLE
[BUG] 스테이지 이동시 사운드 변화 없음

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#114]
# 1. 버그 개요
- 스테이지 이동시 사운드 변화 없음
# 2. 버그 발생 일자
- 2024.11.04 12:55
# 3. 버그 발생 상황 설명
- 1스테이지에서 2스테이지로 넘어갈 때 사운드의 변화가 없음
# 4. 예상되는 문제
- CODE 문제
# 5. 필요한 조치
- CODE 수정
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)
- Window 11 / Unity 2021.3.42f1

**Comment by ohjh1744** [comment]
GameSceneManager쪽에서 _currentStage변수로 수정하여
배경바뀔때마다 BGm바뀌도록 bug 수정.
