### ISSUE TITLE
[BUG] 캐릭터 낙하 속도 버그

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#122]
# 1. 버그 개요
- 캐릭터 낙하시 기획의도와 다르게 캐릭터가 관성을 유지한채 전진하며 추락함
# 2. 버그 발생 일자
- 2024.11.04 12:20
# 3. 버그 발생 상황 설명
- 캐릭터가 플랫폼에서 D키를 누르며 떨어질 때 자연스럽게 추락하지 않고 플랫폼에서의 전진 관성을 유지한 채 추락함
# 4. 예상되는 문제
- code 오류
# 5. 필요한 조치
- 중력의 영향을 받아 자연스럽게 추락하도록 변경
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)
- Window 11 / Unity 2021.3.42f1

**Comment by ohjh1744** [comment]
Platform 스크립트에서 CollisionExit를 통해 Bug 수정했습니다.
내려올때 수직으로 떨어지도록 변경했습니다.
