### ISSUE TITLE
[BUG] 스테이지 세이브가 됐을 때 카메라의 위치가 세이브되지 않은 버그

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#133]
# 1. 버그 개요
- 스테이지 세이브가 됐을 때 카메라의 위치가 세이브되지 않음
# 2. 버그 발생 일자
- 2024.11.05 9:23
# 3. 버그 발생 상황 설명
- 스테이지가 변경된 채로 저장했을 때, Load&Play를 실행할 경우 카메라가 저장된 스테이지로 이동하지 않는 문제
# 4. 예상되는 문제
- 카메라의 좌표값이 저장되지 않는 문제로 예상
# 5. 필요한 조치
- code 수정
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)

**Comment by ohjh1744** [comment]
카메라 위치도 세이브 되도록 수정했습니다
