### ISSUE TITLE
[BUG] Base 캐릭터가 트리거에 계속 걸리는 문제 발생

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#134]
# 1. 버그 개요
- Base 캐릭터가 트리거에 계속 걸리는 문제
# 2. 버그 발생 일자
- 24.11.05 9 : 38
# 3. 버그 발생 상황 설명
- Base 캐릭터가 장애물의 트리거에 곧바로 오버랩되지 않고 걸리는 문제 발생
# 4. 예상되는 문제
- Base 캐릭터 수정 부분에서 고려하지 못한 부분이 있을 것으로 예상
# 5. 필요한 조치
- code 수정
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)

**Comment by ohjh1744** [comment]
Base캐릭터 트리거에 걸려 계속 점프하는 버그 문제 수정했습니다.
