### ISSUE TITLE
일부 Obstacle이 Reset 이후 작동하지 않는 문제

### ISSUE THREAD

**Issue by Jyeon99** [ohjh1744/CAN_UP#135]
# 1. 버그 개요
- 카메라 위치가 변경될 때마다 일부 장애물이 리셋된 후 작동되지 않음
# 2. 버그 발생 일자
- 24.11.05 10:37
# 3. 버그 발생 상황 설명
- 카메라 위치가 변경될 때마다 일부 Obstacle이 원 위치로 리셋된 후 다시 동작하지 않는 문제 발생
# 4. 예상되는 문제
- code 오류
# 5. 필요한 조치
- code 수정
# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)

**Comment by ohjh1744** [comment]
Reset기능 작동하도록 수정했습니다.
