### ISSUE TITLE
[BUG] 방해물 캐릭터와 부딪히지 않은 건

### ISSUE THREAD

**Issue by BomLight** [ohjh1744/CAN_UP#57]
# 1. 버그 개요
- 10월 30일 진행한 현재 구현된 방해물 테스트 中 4번, 5번. 10번 방해물이 캐릭터와 충돌하지 않는 버그 발생.

# 2. 버그 발생 일자
- 2024년 10월 30일 21:00 

# 3. 버그 발생 상황 설명
- 캐릭터를 조작하여 방해물이 발동되는 것까지는 확인했으나, 캐릭터와 충돌하지 않아 그냥 통과해버리는 현상이 나타남.

# 4. 예상되는 문제
- Collider 설정이 잘못되어 있는 것으로 예상

# 5. 필요한 조치
- Collider 관련하여 재조정 필요.

# 6. 현재 사용 중인 OS 및 툴 (버전 기재 필수!)
- Window 11 / Unity Version 2021.3.42f1 / 데스크탑

**Comment by Glaz8212** [comment]
4번 5번 Obstacle 변수 설정 수정해서 해결 완료했습니다.

10번도 Collider 조절 완료 했습니다.
